### ISSUE TITLE
rcpputils/env.hpp: No such file or directory

### ISSUE THREAD

**Issue by Hibanaw** [HorizonRDK/hobot_codec#14]
在RDK X3，ros2 foxy环境中编译develop分支，有以下错误
```
fatal error: rcpputils/env.hpp: No such file or directory
   20 | #include "rcpputils/env.hpp"
      |          ^~~~~~~~~~~~~~~~~~~
```

经检查，foxy版本的rcpputils并没有env.hpp，仅有get_env.hpp，将`rcpputils/env.hpp`改为 `rcpputils/get_env.hpp`后编译通过。

请问develop分支，包括[HorizonRDK/robot_dev_config](HorizonRDK/robot_dev_config)的tros和hobot系列工具的目标ros版本是什么版本，之后版本是否还会向下兼容foxy

**Comment by zhukao** [comment]
tros目前正在基于develop分支适配ros2 humble版本。
每个repo都创建了一个foxy分支，如果您是使用源码编译，请使用foxy分支。未来tros还会继续维护foxy版本。
关于兼容性，ros2的大版本之间不保证兼容，不过从我们适配的过程来看，foxy版本的代码可以直接在humble版本上编译成功，功能也没问题，所以对于应用层来说，实际上是兼容的。
